### ISSUE TITLE
greenlight it on steam

### ISSUE THREAD

**Issue by Extrawurst** [p0nce/Vibrant#1]
be the first D game on steam...
i mean...since we have steam bindings too now :)

**Comment by p0nce** [comment]
Hey, hadn't think of it. Will think about it!

**Comment by Extrawurst** [comment]
Here are the steamworks d bindings:
https://github.com/Extrawurst/DerelictSteamworks

**Comment by p0nce** [comment]
No time for this, and there are already D games on Steam afterall.
