### ISSUE TITLE
libdl is not presented on FreeBSD

### ISSUE THREAD

**Issue by MyLittleRobo** [p0nce/Vibrant#3]
FreeBSD does not use libdl (dlfcn is part of libc).

So "libs-posix":["dl"] in dub.json probably should become libs-linux and libs-osx.

**Comment by p0nce** [comment]
Should be fixed by 46afc1ba7e1f21081363e99f47741fc073a51164

Let me know how it goes on FreeBSD.
On linux there is still a trick of disabling post-processing, I guess FreeBSD may need the same workaround.

**Comment by MyLittleRobo** [comment]
I'm not sure what the trick you're talking about and how to check it.
It seems to run the same as on Linux for me.
Can't run on Windows though. I copied dependencies, but it requires SDL2.dll (there is SDL.dll, not SDL2.dll in dependencies directory).

**Comment by MyLittleRobo** [comment]
I also encountered the issue

Unknown dependency: ae-graphics 

on both FreeBSD and Windows. Second call to dub fixed it though. I guess, it's dub related issue.

**Comment by p0nce** [comment]
I need to update Windows dependencies then, forgot that when going SDL2 for Mac.

Here is the Linux-specific line.
https://github.com/p0nce/Vibrant/blob/master/source/vibrant/vibrantprogram.d#L60

The game looks worse on Linux.

About DUB: the following procedure always work for me:
```
del dub.selections.json
dub clean-caches
```

**Comment by MyLittleRobo** [comment]
I've commented out this trick on Linux. Game still runs as before, no black screen. Some elements like radar and fonts in greeting window look slightly different.

I have GeForce 9600 GT with proprietary nvidia drivers on both Linux and FreeBSD.

**Comment by p0nce** [comment]
I also have a NVIDIA and had the problem on Linux, and somebody else also had.
I'd prefer to let the workaround in place for now, but not on FreeBSD.

**Comment by p0nce** [comment]
About FreeBSD: does it work there? What are the libraries to install?

**Comment by MyLittleRobo** [comment]
It works flawlessly on FreeBSD 10 x86. Compiled with dmd 2.067.0

I guess sdl2 and sdl2_mixer would be enough. They can be installed via pkg:

```
pkg install sdl2 sdl2_mixer
```
